Basic Tensor Arithmetic
 (The Hadamard Product)




In [ ]:
import numpy as np
import torch
import tensorflow as tf

In [ ]:
#1.) buat matrix X dengan ukuran 2x3 menggunakan numpy
x = np.array([[21,31,41],[51,61,71]])
x

array([[21, 31, 41],
       [51, 61, 71]])

In [ ]:
#buat matrix X_pt dengan ukuran 2x3 menggunakan pytorch
x_pt = torch.tensor([[10,20,30],[40,50,60]])
x_pt

tensor([[10, 20, 30],
        [40, 50, 60]])

In [ ]:
#buat matrix X_tf dengan ukuran 2x3 menggunakan tensorflow
x_tf = tf.Variable([[2,4,6],[8,10,12]])
x_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[ 2,  4,  6],
       [ 8, 10, 12]], dtype=int32)>

In [ ]:
#lakukan perkalian matrix X, X_pt dan X_tf dengan suatu skalar
x
x_pt_np = x_pt.numpy()
x_tf
x * x_pt_np * x_tf

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[  420,  2480,  7380],
       [16320, 30500, 51120]], dtype=int32)>

In [ ]:
#lakukan penjumlahan matrix X, X_pt dan X_tf dengan suatu skalar
x + x_pt_np + x_tf

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 33,  55,  77],
       [ 99, 121, 143]], dtype=int32)>

In [ ]:
#lakukan pengurangan matrix X, X_pt dan X_tf dengan suatu skalar
x - x_pt_np - x_tf

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 9,  7,  5],
       [ 3,  1, -1]], dtype=int32)>

In [ ]:
#2.) buat matrix Y dengan ukuran 2x3 menggunakan numpy
y = np.array([[9,8,7],[6,5,4]])
y

array([[9, 8, 7],
       [6, 5, 4]])

In [ ]:
#buat matrix Y_pt dengan ukuran 2x3 menggunakan pytorch
y_pt = torch.tensor([[12,21,23],[34,43,45]])
y_pt

tensor([[12, 21, 23],
        [34, 43, 45]])

In [ ]:
#buat matrix Y_tf dengan ukuran 2x3 menggunakan tensorflow
y_tf = tf.Variable([[15,25,35],[42,52,62]])
y_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[15, 25, 35],
       [42, 52, 62]], dtype=int32)>

In [ ]:
#kalikan matrix X dengan Y
x * y

array([[189, 248, 287],
       [306, 305, 284]])

In [ ]:
#kalikan matrix X_pt dengan Y_pt
x_pt * y_pt

tensor([[ 120,  420,  690],
        [1360, 2150, 2700]])

In [ ]:
#kalikan matrix X_tf dengan Y_tf
x_tf * y_tf

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 30, 100, 210],
       [336, 520, 744]], dtype=int32)>