Tensor Reduction

In [2]:
#1.) buat matrix X dengan ukuran 2x3 menggunakan numpy
import numpy as np
x = np.array([[10,20,30], [40,50,60]])
x

array([[10, 20, 30],
       [40, 50, 60]])

In [3]:
#hitung berapa hasil penjumlahan elemen matrix X dengan fungsi sum
x.sum()

np.int64(210)

In [4]:
#buat matrix X_tf dengan ukuran 2x3 menggunakan tensorflow
import tensorflow as tf
x_tf = tf.Variable([[11,12,13],[14,15,16]])
x_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[11, 12, 13],
       [14, 15, 16]], dtype=int32)>

In [5]:
#2.) hitung hasil penjumlahan seluruh elemen matrix X
x.sum()

np.int64(210)

In [6]:
#hitung hasil penjumlahan seluruh elemen matrix X_pt
import torch
x_pt = torch.tensor([[52,10,25],[90,60,42.]])
x_pt.sum()

tensor(279.)

In [7]:
#hitung hasil penjumlahan seluruh elemen matrix X_tf
tf.reduce_sum(x_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=81>

In [8]:
#3.) hitung hasil penjumlahan matrix X berdasarkan row nya
x.sum(axis=1)

array([ 60, 150])

In [9]:
#hitung hasil penjumlahan matrix X_pt berdasarkan row nya
x_pt.sum(axis=1)

tensor([ 87., 192.])

In [10]:
#hitung hasil penjumlahan matrix X_tf berdasarkan row nya
tf.reduce_sum(x_tf, axis = 1)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([36, 45], dtype=int32)>

In [11]:
#4.) hitung hasil penjumlahan matrix X berdasarkan kolom nya
x.sum(axis=0)

array([50, 70, 90])

In [12]:
#hitung hasil penjumlahan matrix X_pt berdasarkan kolom nya
x_pt.sum(axis=0)

tensor([142.,  70.,  67.])

In [13]:
#hitung hasil penjumlahan matrix X_tf berdasarkan kolom nya
tf.reduce_sum(x_tf, axis = 0)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([25, 27, 29], dtype=int32)>

In [14]:
#5.) hitung nilai minimal dari matrix X, X_pt dan X_tf
print(x.min())
print(x_pt.min())
print(tf.reduce_min(x_tf))

10
tensor(10.)
tf.Tensor(11, shape=(), dtype=int32)


In [15]:
#hitung nilai maksimal dari matrix X, X_pt dan X_tf
print(x.max())
print(x_pt.max())
print(tf.reduce_max(x_tf))

60
tensor(90.)
tf.Tensor(16, shape=(), dtype=int32)


In [16]:
#hitung nilai rata-rata dari matrix X, X_pt dan X_tf
print(x.mean())
print(x_pt.mean())
print(tf.reduce_mean(x_tf))

35.0
tensor(46.5000)
tf.Tensor(13, shape=(), dtype=int32)


In [ ]:
#6.) hitung hasil perkalian seluruh elemen matrix X
x.prod()

np.int64(720000000)

In [ ]:
#hitung hasil perkalian seluruh elemen matrix X_pt
x_pt.prod()

tensor(2948400000)

In [ ]:
#hitung hasil perkalian seluruh elemen matrix X_tf
tf.math.reduce_prod(x_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=5765760>