Tensor Transposition

In [ ]:
import numpy as np
import torch
import tensorflow as tf

In [ ]:
#1.) buat matrix X dengan ukuran 2x3 menggunakan numpy
x = np.array([[10,20,30],[40,50,60]])
x

array([[10, 20, 30],
       [40, 50, 60]])

In [ ]:
#buat matrix X_pt dengan ukuran 2x3 menggunakan pytorch
x_pt = torch.tensor([[12,13,14],[15,16,17]])
x_pt

tensor([[12, 13, 14],
        [15, 16, 17]])

In [ ]:
#buat matrix X_tf dengan ukuran 2x3 menggunakan tensorflow
x_tf = tf.Variable([[18,19,20],[21,22,23]])
x_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[18, 19, 20],
       [21, 22, 23]], dtype=int32)>

In [ ]:
#2.) lakukan transpose pada matrix X, X_pt dan X_tf
x_t = x.T
x_pt_t = x_pt.T
x_tf_t = tf.transpose(x_tf)
print(x_t)
print(x_pt_t)
print(x_tf_t)

[[10 40]
 [20 50]
 [30 60]]
tensor([[12, 15],
        [13, 16],
        [14, 17]])
tf.Tensor(
[[18 21]
 [19 22]
 [20 23]], shape=(3, 2), dtype=int32)
