Matrix Tensors

In [2]:
import numpy as np

In [4]:
#1.) buat matrix X berukuran 2x3 menggunakan numpy
x = np.array([[25,15,66], [52,51,66]])
x

array([[25, 15, 66],
       [52, 51, 66]])

In [5]:
#tampilkan ukuran dari matrix X
x.shape

(2, 3)

In [7]:
#tampilkan seluruh elemen dari kolom pertama dari matrix X
x[:,0]

array([25, 52])

In [12]:
#tampilkan seluruh elemen dari baris kedua dari matrix X
x[1,:]

array([52, 51, 66])

In [23]:
#2.) ulangi soal nomor 1 menggunakan pytorch
#ulangi soal nomor 1 menggunakan tensorflow
import torch
import tensorflow as tf

In [24]:
#buat matrix X berukuran 2x3 menggunakan pytorch
x_pt = torch.tensor([[25,15,66], [52,51,66]])
x_pt

tensor([[25, 15, 66],
        [52, 51, 66]])

In [25]:
#tampilkan ukuran dari matrix x_pt
x_pt.shape

torch.Size([2, 3])

In [26]:
#tampilkan seluruh elemen dari kolom pertama dari matrix x_pt
x_pt[:,0]

tensor([25, 52])

In [27]:
#tampilkan seluruh elemen dari baris kedua dari matrix x_pt
x_pt[1,:]

tensor([52, 51, 66])

In [28]:
#buat matrix X berukuran 2x3 menggunakan tensorflow
x_tf = tf.Variable([[25,15,66], [52,51,66]])
x_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[25, 15, 66],
       [52, 51, 66]], dtype=int32)>

In [29]:
#tampilkan ukuran dari matrix x_tf
x_tf.shape

TensorShape([2, 3])

In [30]:
#tampilkan seluruh elemen dari kolom pertama dari matrix x_tf
x_tf[:,0]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([25, 52], dtype=int32)>

In [31]:
#tampilkan seluruh elemen dari baris kedua dari matrix x_tf
x_tf[1,:]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([52, 51, 66], dtype=int32)>