
Vectors and Vector Transposition



In [1]:
import numpy as np

In [6]:
#1.) buat vector x dengan ukuran 3x1
x = np.array([25,15,66])
x

array([25, 15, 66])

In [7]:
#hitung panjang vector x
len(x)

3

In [8]:
#tampilkan ukuran vector x
x.shape

(3,)

In [9]:
#tampilkan tipe data dari vector x
type(x)

numpy.ndarray

In [10]:
#akses elemen pertama dari vector x
x[0]

np.int64(25)

In [11]:
#tampilkan tipe data elemen pertama dari vector x
type(x[0])

numpy.int64

In [12]:
#2.) lakukan transpose pada vector x dan simpan pada variabel x_t
x_t = x.T
x_t

array([25, 15, 66])

In [14]:
#tampilkan ukuran dari vector x_t
x_t.shape

(3,)

In [21]:
#lakukan transpose pada vector y dan simpan pada variabel y_t
y = np.array([[25,15,66], [52,51,66]])
y_t = y.T
y_t

array([[25, 52],
       [15, 51],
       [66, 66]])

In [22]:
#tampilkan ukuran dari vector y_t
y_t.shape

(3, 2)

In [23]:
#3.) lakukan soal nomor 2 menggunakan pytorch dan tensorflow
import torch
import tensorflow as tf


In [28]:
#lakukan transpose pada vector x_pt dan simpan pada variabel x_pt_t
x_pt = torch.tensor([25, 15, 66])
x_pt_t = x_pt.T
x_pt_t

tensor([25, 15, 66])

In [29]:
#tampilkan ukuran dari vector x_pt_t
x_pt_t.shape

torch.Size([3])

In [34]:
#lakukan transpose pada vector y_pt dan simpan pada variabel y_pt_t
y_pt = torch.tensor([[25, 15, 66], [52,51,66]])
y_pt_t = y_pt.T
y_pt_t

tensor([[25, 52],
        [15, 51],
        [66, 66]])

In [35]:
#tampilkan ukuran dari vector y_pt_t
y_pt_t.shape

torch.Size([3, 2])

In [37]:
#lakukan transpose pada vector x_tf dan simpan pada variabel x_tf_t
x_tf = tf.Variable([25,15,66])
x_tf_t = tf.transpose(x_tf)
x_tf_t

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([25, 15, 66], dtype=int32)>

In [38]:
#tampilkan ukuran dari vector x_tf_t
x_tf_t.shape

TensorShape([3])

In [39]:
#lakukan transpose pada vector y_tf dan simpan pada variabel y_tf_t
y_tf = tf.Variable([[25,15,66], [52,51,66]])
y_tf_t = tf.transpose(y_tf)
y_tf_t

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[25, 52],
       [15, 51],
       [66, 66]], dtype=int32)>

In [40]:
#tampilkan ukuran dari vector y_tf_t
y_tf_t.shape

TensorShape([3, 2])