In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#buat matrix X ukuran 2x2 menggunakan numpy
X = np.array([[2, 6], [-3, -7]])
X = np.matrix(X)
X



matrix([[ 2,  6],
        [-3, -7]])

In [3]:
#buat invers dari matrix X dan beri nama Xinv menggunakan numpy
Xinv = np.linalg.inv(X)
Xinv

matrix([[-1.75, -1.5 ],
        [ 0.75,  0.5 ]])

In [5]:
#kalikan X dengan Xinv menggunakan numpy
np.dot(X, Xinv)

matrix([[ 1.00000000e+00,  0.00000000e+00],
        [-3.33066907e-16,  1.00000000e+00]])

In [6]:
#selesaikan persamaan berikut menggunakan numpy, tensorflow dan pytorch

import numpy as np

A = np.array([[4, 2],
              [-5, -3]])
B = np.array([4, -7])

# Mencari solusi x
x = np.linalg.solve(A, B)

print(f"NumPy Solution: b = {x[0]:.2f}, c = {x[1]:.2f}")

import tensorflow as tf

A = tf.constant([[4.0, 2.0],
                 [-5.0, -3.0]])
B = tf.constant([[4.0],
                 [-7.0]])

# Mencari solusi x
x = tf.linalg.solve(A, B)

print(f"TensorFlow Solution: b = {x[0][0]:.2f}, c = {x[1][0]:.2f}")

import torch

A = torch.tensor([[4.0, 2.0],
                  [-5.0, -3.0]])
B = torch.tensor([4.0, -7.0])

# Mencari solusi x
x = torch.linalg.solve(A, B)

print(f"PyTorch Solution: b = {x[0]:.2f}, c = {x[1]:.2f}")

NumPy Solution: b = -1.00, c = 4.00
TensorFlow Solution: b = -1.00, c = 4.00
PyTorch Solution: b = -1.00, c = 4.00
