# **24.Matrix Multiplication**

In [ ]:
#buat matrix A dengan ukuran 2x3 dan vector b berukuran 3x1 menggunakan numpy
import numpy as np
A = np.array([[1,2,3],[4,5,6]])
b = np.array([[1],[2],[3]])
A, b

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1],
        [2],
        [3]]))

In [ ]:
#buat matrix A_pt dengan ukuran 2x3 dan vector b_pt berukuran 3x1 menggunakan pytorch
import torch
A_pt = torch.tensor([[1,2,3],[4,5,6]])
b_pt = torch.tensor([[1],[2],[3]])
A_pt, b_pt

(tensor([[1, 2, 3],
         [4, 5, 6]]),
 tensor([[1],
         [2],
         [3]]))

In [ ]:
#buat matrix A_tf dengan ukuran 2x3 dan vector b_tf berukuran 3x1 menggunakan tensorflow
import tensorflow as tf
A_tf = tf.Variable([[1,2,3], [4,5,6]])
b_tf = tf.Variable([[1], [2], [3]])
A_tf, b_tf

(<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>,
 <tf.Variable 'Variable:0' shape=(3, 1) dtype=int32, numpy=
 array([[1],
        [2],
        [3]], dtype=int32)>)

In [ ]:
#tampilkan ukuran matrix A dan vector b
print(A.shape)
print(b.shape)


(2, 3)
(3, 1)


In [ ]:
#kalikan matrix A dengan vector b
np.dot(A,b)

array([[14],
       [32]])

In [ ]:
#kalikan matrix A_pt dengan vector b_pt
torch.matmul(A_pt,b_pt)

tensor([[14],
        [32]])

In [ ]:
#kalikan matrix A_tf dengan vector b_tf
tf.matmul(A_tf,b_tf)

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[14],
       [32]], dtype=int32)>

In [ ]:
#buat matrix B dengan ukuran 3x3 menggunakan numpy
B = np.array([[1,2,3],[4,5,6],[7,8,9]])
B

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#buat matrix B_pt dengan ukuran 3x3 menggunakan pytorch
B_pt = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
B_pt

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
#buat matrix B_tf dengan ukuran 3x3 menggunakan tensorflow
B_tf = tf.Variable([[1,2,3],[4,5,6],[7,8,9]])
B_tf

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [ ]:
#kalikan matrix A dengan matrix B
np.dot(A,B)

array([[30, 36, 42],
       [66, 81, 96]])

In [ ]:
#kalikan matrix A_pt dengan matrix B_pt
torch.matmul(A_pt,B_pt)

tensor([[30, 36, 42],
        [66, 81, 96]])

In [ ]:
#kalikan matrix A_tf dengan matrix B_tf
tf.matmul(A_tf,B_tf)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[30, 36, 42],
       [66, 81, 96]], dtype=int32)>

In [ ]:
#buktikan apakah perkalian matrix bersifat komutatif? (AB=BA)?
np.dot(A,B) == np.dot(B,A)

NameError: name 'B' is not defined