Matrix Multiplication Exercises

In [1]:
import torch

In [5]:
#1.) lakukan perhitungan soal excercise menggunakan collab
x = torch.tensor([[0,1,2],[3,4,5],[6,7,8]])
y = torch.tensor([[-1,1,-2]]).T
print(x)
print(y)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[-1],
        [ 1],
        [-2]])


In [6]:
torch.matmul(x,y)

tensor([[ -3],
        [ -9],
        [-15]])

In [13]:
#2.)Repeat Q1 using the same vector but replace matrix with I₃
I = torch.tensor([[1,0,0],[0,1,0],[0,0,1]]).T
torch.matmul(I,y)

tensor([[-1],
        [ 1],
        [-2]])

In [22]:
#3.)
v = torch.tensor([[0,1,2],[3,4,5],[6,7,8]])
w = torch.tensor([[-1,0],[1,1],[-2,2]])
print(v)
print(w)
torch.matmul(v,w)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[-1,  0],
        [ 1,  1],
        [-2,  2]])


tensor([[ -3,   5],
        [ -9,  14],
        [-15,  23]])