Symmetric Matrices

In [1]:
import numpy as np

In [6]:
# buatlah matriks simetris dengan ukuran 3x3 dan buktikan bahwa itu merupakan matriks simetris
X_sym = np.array([[0, 1, 2,], [1, 7, 8], [2, 8 , 9]])
X_sym

array([[0, 1, 2],
       [1, 7, 8],
       [2, 8, 9]])

In [7]:
X_sym.T

array([[0, 1, 2],
       [1, 7, 8],
       [2, 8, 9]])

In [8]:
X_sym.T == X_sym

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

Identity Matrices

In [22]:
import torch

In [11]:
# buatlah matriks identitas I dengan ukuran 4x4 menggunakan pytorch
I = torch.tensor ([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]])
I

tensor([[1, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1]])

In [17]:
# buatlah vector b_pt dengan ukuran 4x1
b_pt = torch.tensor([[7],
                     [1],
                     [9],
                     [3]])
b_pt

tensor([[7],
        [1],
        [9],
        [3]])

In [21]:
# kalikan matrix I dengan vector b_pt
torch.matmul(I, b_pt)

tensor([[7],
        [1],
        [9],
        [3]])